project_id = "sbyslxhjjfcqlxaehidw"

[functions.analyze-conversation]
verify_jwt = true

[functions.process-scheduled-messages]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.uazapi-instance]
verify_jwt = false

[functions.uazapi-webhook]
verify_jwt = false

[functions.uazapi-send]
verify_jwt = false
